apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace:  expense
  # These labels are deployment resource labels
  labels:
    app: frontend
    tier: web
    project:  expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      tier: web
      project:  expense  
  template:
    metadata:
      labels:
       app: frontend
       tier: web
       project:  expense
    spec:
      containers:
      - name: nginx
        image: joindevops/frontend:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector: 
    app: frontend
    tier: web
    project:  expense
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80
       