apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace:  expense
  # These labels are deployment resource labels
  labels:
    app: backend
    tier: backend
    project:  expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
      project:  expense  
  template:
    metadata:
      labels:
       app: backend
       tier: backend
       project:  expense
    spec:
      containers:
      - name: nginx
        image: joindevops/backend:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector: 
    app: backend
    tier: backend
    project:  expense
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080
       