apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace:  expense
  # These labels are deployment resource labels
  labels:
    app: mysql
    tier: mysql
    project:  expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: mysql
      project:  expense  
  template:
    metadata:
      labels:
       app: mysql
       tier: mysql
       project:  expense
    spec:
      containers:
      - name: nginx
        image: joindevops/mysql:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector: 
    app: mysql
    tier: mysql
    project:  expense
  ports:
    - protocol: TCP
      port: 3306 # service port
      targetPort: 3306
       